; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ltumnfriscv64 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64

; Materializing constants

define i32 @zero() nounwind {
; RV64-LABEL: zero:
; RV64:       # %bb.0:
; RV64-NEXT:    li a0, 0
; RV64-NEXT:    ret
  ret i32 0
}

define i32 @pos_small() nounwind {
; RV64-LABEL: pos_small:
; RV64:       # %bb.0:
; RV64-NEXT:    li a0, 2047
; RV64-NEXT:    ret
  ret i32 2047
}

define i32 @neg_small() nounwind {
; RV64-LABEL: neg_small:
; RV64:       # %bb.0:
; RV64-NEXT:    li a0, -2048
; RV64-NEXT:    ret
  ret i32 -2048
}

define i32 @pos_i32() nounwind {
; RV64-LABEL: pos_i32:
; RV64:       # %bb.0:
; RV64-NEXT:    lui a0, 423811
; RV64-NEXT:    addi a0, a0, -1297
; RV64-NEXT:    ret
  ret i32 1735928559
}

define i32 @neg_i32() nounwind {
; RV64-LABEL: neg_i32:
; RV64:       # %bb.0:
; RV64-NEXT:    lui a0, 912092
; RV64-NEXT:    addi a0, a0, -273
; RV64-NEXT:    ret
  ret i32 -559038737
}
